### ISSUE TITLE
Bot not responding to anything

### ISSUE THREAD

**Issue by S14ontop** [yannismate/yannismate-api#1]
i have added the rocketrankbot as a moderator and also typed the command !join but nothing i tried some of the other commands like @rocketrankbot !setplatform epic and still nothing
could i get some help on this please

**Comment by yannismate** [comment]
Hey! What's your Twitch channel? I'll have a look at it.

**Comment by S14ontop** [comment]
hi , i have actually fixed this earlier this morning with help from another streamer who uses the bot.
